### PR TITLE
F/saved news

### LINKED ISSUE #75: Ability to save articles
Something like feedly, but without cloud sync support, local storage will do.

### PR DESCRIPTION
**Pull request by timotiusnc**
Fixes #75

### CODE REVIEW

**Comment by wiseodd** [comment]
Better to use snackbar than toast. Also having "UNDO" button in snackbar is very useful.
Try GMail app deletion behavior for example.

**Comment by wiseodd** [comment]
Also, how can user un-save the news?

I think we need to put that mechanism.
Maybe use the same button, but change it to "Unsave" when we know that it's been saved.
Or maybe you have better idea.

**Comment by wiseodd** [comment]
One more thing.

The order of Saved News list should be chronological with regard of when user save the news.
It would be confusing if user browsed news no. 497, and save it, then when she goes to Saved News, she sees nothing.

**Comment by wiseodd** [comment]
Going to implement the snackbar

**Comment by timotiusnc** [comment]
U-u-updateeed!!

**Comment by wiseodd** [comment]
Prima!
I'm going to merge this!

**Pull request merged**
