### PR TITLE
Handle configuration changes properly

### PR DESCRIPTION
**Pull request by timotiusnc**
Handled on NewsListFragment and NewsDetailFragment.

It's a bit slower than `android:configChanges="orientation|screenSize"`, but that needs to be removed for tablet support.

@wiseodd

### CODE REVIEW

**Comment by wiseodd** [comment]
It has some deal breaking compromises, by handling orientation change this way:
1. While loading, change device orientation, it won't continue loading
2. Integrated web view reload when changing device orientation

I feel like this is less robust than using android:configChanges

**Comment by timotiusnc** [comment]
OK, I will handle that changes too.

I think using `android:configChanges` is not possible if we want to support multiple screen. If we use that, Android will not restart the activity when there's orientation change and thus will use the incorrect xml layout.

[There's a good StackOverflow question here about this issue](http://stackoverflow.com/questions/7818717/why-not-use-always-androidconfigchanges-keyboardhiddenorientation).

**Comment by timotiusnc** [comment]
For future reference

WebView handle rotation:
https://groups.google.com/forum/#!msg/android-developers/cWnxkQ8RLeY/RA1n77EDeR8J

ViewPagerAdapter:
http://stackoverflow.com/questions/14789519/fragment-getview-always-returning-null-for-fragments-created-by-a-fragmentstat
http://stackoverflow.com/questions/19107612/fragment-inside-viewpager-returning-null-in-getview

**Comment by timotiusnc** [comment]
Ready to be reviewed again!

For integrated webview, it turned out it's the expected behavior from Android (to refresh everytime there's a config changes). But we can still preserve the state (if user follow any other link, it will refresh to that link after config changes, the webview will also remember the history for back button purpose).

More detailed info at https://groups.google.com/forum/#!msg/android-developers/cWnxkQ8RLeY/RA1n77EDeR8J

**Comment by wiseodd** [comment]
Nicely done!

**Pull request merged**
