### PR TITLE
Settings UI

### PR DESCRIPTION
**Pull request by wiseodd**
Checkout the settings, and try to change the preference there.
For starter, there is only one preference: smaller text size.
If it's checked, the title font size in news list and news detail should be smaller (14sp) compared to default (16sp).

### CODE REVIEW

**Comment by timotiusnc** [comment]
Unable to merge

**Comment by wiseodd** [comment]
@timotiusnc updated

**Comment by timotiusnc** [comment]
Still unable to merge.

**Comment by wiseodd** [comment]
Shite

**Comment by wiseodd** [comment]
Updated

**Pull request merged**
