### PR TITLE
[UI] Closes #83: Use collapsing toolbar

### LINKED ISSUE #83: Revisit the use of collapsing action bar
Move share and save and open with browser button to action bar menu.

### PR DESCRIPTION
**Pull request by wiseodd**
@timotiusnc 
Please review and test

### CODE REVIEW

**Comment by timotiusnc** [comment]
I think it's better to differentiate saved and unsaved news icon.
For unsaved news, it could use [bookmark border](https://www.google.com/design/icons/#ic_bookmark_border) icon.

**Comment by wiseodd** [comment]
Hmm, it could be either way, depending on our perspective.

Here's the alternative:
Bookmark border for save, bookmark for unsave.
We're representing the state, not the action. Unsave is bookmark because the state is saved.

What do you think is better?

**Comment by timotiusnc** [comment]
The one representing state (bookmark for saved news; bookmark border for unsaved news).
I used Medium Android app as benchmark.

**Comment by wiseodd** [comment]
GOGOGO

**Pull request merged**
