### PR TITLE
Side Nav UI

### PR DESCRIPTION
**Pull request by wiseodd**
2-sidenav-white copy

### CODE REVIEW

**Comment by timotiusnc** [comment]
Where did you get all the icons?

I thought there will be a library like font-awesome for Android which compress all icons into one font file and then we can display it by specifying its ID. (or is it still too early for Android?)

**Comment by timotiusnc** [comment]
Hoah, soo many nitty gritty in Android UI, I guess I can only black box test it.
What do you think?

**Comment by wiseodd** [comment]
Icons: https://www.google.com/design/icons/
I don't think Android use icon fonts.
It's either SVG or PNG.

Yes of course, there are a lot scaffolding results here in my code.

**Comment by wiseodd** [comment]
Updated

**Pull request merged**
